/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffddb4',
        'on-secondary': '#452b00',
        'on-background': '#e5e2e1',
        'on-primary-fixed-variant': '#633f00',
        'primary-fixed': '#ffddb4',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#004c69',
        'on-tertiary-container': '#004d6a',
        'error': '#ffb4ab',
        'on-primary': '#452b00',
        'tertiary': '#9bd9ff',
        'on-secondary-container': '#d9ae75',
        'primary': '#ffc880',
        'surface': '#131313',
        'inverse-surface': '#e5e2e1',
        'surface-container-low': '#1c1b1b',
        'surface-tint': '#ffb955',
        'on-primary-container': '#644000',
        'on-error': '#690005',
        'on-surface': '#e5e2e1',
        'surface-container': '#201f1f',
        'inverse-primary': '#835500',
        'secondary-fixed-dim': '#ecbf85',
        'background': '#0D0D0D',
        'tertiary-fixed-dim': '#7cd0ff',
        'outline-variant': '#524534',
        'on-primary-fixed': '#291800',
        'secondary-container': '#5f4112',
        'secondary': '#ecbf85',
        'primary-container': '#f5a623',
        'on-secondary-fixed-variant': '#5f4112',
        'on-secondary-fixed': '#291800',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#00344a',
        'surface-bright': '#3a3939',
        'inverse-on-surface': '#313030',
        'surface-variant': '#353534',
        'on-surface-variant': '#d7c3ae',
        'outline': '#9f8e7a',
        'surface-container-highest': '#353534',
        'primary-fixed-dim': '#ffb955',
        'tertiary-fixed': '#c4e7ff',
        'on-tertiary-fixed': '#001e2c',
        'surface-dim': '#131313',
        'tertiary-container': '#3ac2ff',
        'error-container': '#93000a',
        'surface-container-lowest': '#0e0e0e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}
